/**
 * Compare magnetic fields generated by Coil and Magnet classes
 * Plots B_x vs x, B_y vs x, B_x vs y, B_y vs y for both objects
 * 
 * This script uses the JavaScript implementations from the frontend
 */

import fs from 'fs';
import { Coil, Magnet } from './frontend/src/physics/objects.js';

const MU_0 = 4 * Math.PI * 1e-7;

// Parameters for equivalent Coil and Magnet
// Using equation: moment = N * I * S
const coilParams = {
    x: 0.0,
    y: 0.0,
    radius: 0.03,      // 3 cm
    length: 0.05,      // 5 cm
    nTurns: 100,
    current: 2.0,      // 2 A
    mu: MU_0
};

// Calculate equivalent moment: m = NIS = NI * π * r²
const surface = Math.PI * coilParams.radius * coilParams.radius;
const moment = coilParams.nTurns * coilParams.current * surface;

const magnetParams = {
    x: 0.0,
    y: 0.0,
    radius: coilParams.radius,
    length: coilParams.length,
    n_x: 100,
    n_y: 200,
    moment: moment,
    angle: 90,  // aligned along y-axis like the coil
    mu: MU_0
};

console.log(`Coil parameters: N=${coilParams.nTurns}, I=${coilParams.current}A, R=${coilParams.radius}m, L=${coilParams.length}m`);
console.log(`Surface S = π*R² = ${surface.toExponential(3)} m²`);
console.log(`Equivalent moment = N*I*S = ${moment.toExponential(3)} A·m²`);
console.log('');

// Create objects
const coil = new Coil(
    coilParams.x,
    coilParams.y,
    coilParams.radius,
    coilParams.length,
    coilParams.nTurns,
    coilParams.current,
    coilParams.mu
);

const magnet = new Magnet(
    magnetParams.x,
    magnetParams.y,
    magnetParams.radius,
    magnetParams.length,
    magnetParams.n_x,
    magnetParams.n_y,
    magnetParams.moment,
    magnetParams.angle,
    magnetParams.mu
);

// Generate data for plots
const numPoints = 100;


// B_x vs x (at y = 0)
const xRange = { min: -0.1, max: 0.1 };
const xValues = [];
const coilBx_vs_x = [];
const magnetBx_vs_x = [];

for (let i = 0; i < numPoints; i++) {
    const x = xRange.min + (xRange.max - xRange.min) * i / (numPoints - 1);
    xValues.push(x);
    
    const coilField = coil.field(x, 0);
    coilBx_vs_x.push(coilField.Bx);
    
    const magnetField = magnet.field(x, 0);
    magnetBx_vs_x.push(magnetField.Bx);
}


// B_y vs x (at y = 0)
const coilBy_vs_x = [];
const magnetBy_vs_x = [];

for (let i = 0; i < numPoints; i++) {
    const x = xRange.min + (xRange.max - xRange.min) * i / (numPoints - 1);
    
    const coilField = coil.field(x, 0);
    coilBy_vs_x.push(coilField.By);
    
    const magnetField = magnet.field(x, 0);
    magnetBy_vs_x.push(magnetField.By);
}


// B_x vs y (at x = 0)
const yRange = { min: -0.1, max: 0.1 };
const yValues = [];
const coilBx_vs_y = [];
const magnetBx_vs_y = [];

for (let i = 0; i < numPoints; i++) {
    const y = yRange.min + (yRange.max - yRange.min) * i / (numPoints - 1);
    yValues.push(y);
    
    const coilField = coil.field(0, y);
    coilBx_vs_y.push(coilField.Bx);
    
    const magnetField = magnet.field(0, y);
    magnetBx_vs_y.push(magnetField.Bx);
}


// B_y vs y (at x = 0)
const coilBy_vs_y = [];
const magnetBy_vs_y = [];

for (let i = 0; i < numPoints; i++) {
    const y = yRange.min + (yRange.max - yRange.min) * i / (numPoints - 1);
    
    const coilField = coil.field(0.001, y);
    coilBy_vs_y.push(coilField.By);
    
    const magnetField = magnet.field(0.0, y);
    magnetBy_vs_y.push(magnetField.By);
}


// Save data as JSON for Python plotting
const data = {
    params: {
        coil: coilParams,
        magnet: magnetParams,
        moment: moment,
        surface: surface
    },
    xValues,
    yValues,
    coil: {
        Bx_vs_x: coilBx_vs_x,
        By_vs_x: coilBy_vs_x,
        Bx_vs_y: coilBx_vs_y,
        By_vs_y: coilBy_vs_y
    },
    magnet: {
        Bx_vs_x: magnetBx_vs_x,
        By_vs_x: magnetBy_vs_x,
        Bx_vs_y: magnetBx_vs_y,
        By_vs_y: magnetBy_vs_y
    }
};

fs.writeFileSync('compare_data.json', JSON.stringify(data, null, 2));
console.log('Data saved to compare_data.json');
