"""
Plot comparison of magnetic fields from Coil and Magnet classes
Reads data from field_comparison_data.json generated by compare_fields.js
"""

import json
import matplotlib.pyplot as plt
import numpy as np

# Read data from JSON file
with open('compare_data.json', 'r') as f:
    data = json.load(f)

# Extract data
xValues = np.array(data['xValues'])
yValues = np.array(data['yValues'])

coil_Bx_vs_x = np.array(data['coil']['Bx_vs_x'])
coil_By_vs_x = np.array(data['coil']['By_vs_x'])
coil_Bx_vs_y = np.array(data['coil']['Bx_vs_y'])
coil_By_vs_y = np.array(data['coil']['By_vs_y'])

magnet_Bx_vs_x = np.array(data['magnet']['Bx_vs_x'])
magnet_By_vs_x = np.array(data['magnet']['By_vs_x'])
magnet_Bx_vs_y = np.array(data['magnet']['Bx_vs_y'])
magnet_By_vs_y = np.array(data['magnet']['By_vs_y'])

params = data['params']



# Create figure with 2x4 subplots
fig, axes = plt.subplots(2, 4, figsize=(20, 10))
fig.suptitle(f'Magnetic Field Comparison: Coil vs Magnet', fontsize=16, fontweight='bold')

# Add parameter text box
coil_text = f"""Coil Parameters:
R = {params['coil']['radius']*1000:.1f} mm
L = {params['coil']['length']*1000:.1f} mm
S = {params['surface']:.2e} m²
N = {params['coil']['nTurns']} turns
I = {params['coil']['current']} A"""

magnet_text=f"""Magnet Parameters:
R = {params['magnet']['radius']*1000:.1f} mm
L = {params['magnet']['length']*1000:.1f} mm
n_x × n_y = {params['magnet']['n_x']} × {params['magnet']['n_y']}
moment = {params['moment']:.2f} A·m²"""


plt.figtext(0.81, 0.905, coil_text, fontsize=9, family='monospace',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.3),
            verticalalignment='bottom', horizontalalignment='right')
plt.figtext(0.93, 0.92, magnet_text, fontsize=9, family='monospace',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.3),
            verticalalignment='bottom', horizontalalignment='right')



# Coil plots (top row)
# B_x vs x
axes[0, 0].plot(xValues * 1000, coil_Bx_vs_x * 1000, 'b-', linewidth=2, label='Coil')
axes[0, 0].set_xlabel('x [mm]')
axes[0, 0].set_ylabel('$B_x$ [mT]')
axes[0, 0].set_title('Coil: $B_x$ vs x (at y=0)')
axes[0, 0].grid(True, alpha=0.3)
axes[0, 0].axhline(y=0, color='k', linestyle='--', linewidth=0.5)
axes[0, 0].axvline(x=0, color='k', linestyle='--', linewidth=0.5)

# B_y vs x
axes[0, 1].plot(xValues * 1000, coil_By_vs_x * 1000, 'b-', linewidth=2, label='Coil')
axes[0, 1].set_xlabel('x [mm]')
axes[0, 1].set_ylabel('$B_y$ [mT]')
axes[0, 1].set_title('Coil: $B_y$ vs x (at y=0)')
axes[0, 1].grid(True, alpha=0.3)
axes[0, 1].axhline(y=0, color='k', linestyle='--', linewidth=0.5)
axes[0, 1].axvline(x=0, color='k', linestyle='--', linewidth=0.5)

# B_x vs y
axes[0, 2].plot(yValues * 1000, coil_Bx_vs_y * 1000, 'b-', linewidth=2, label='Coil')
axes[0, 2].set_xlabel('y [mm]')
axes[0, 2].set_ylabel('$B_x$ [mT]')
axes[0, 2].set_title('Coil: $B_x$ vs y (at x=0)')
axes[0, 2].grid(True, alpha=0.3)
axes[0, 2].axhline(y=0, color='k', linestyle='--', linewidth=0.5)
axes[0, 2].axvline(x=0, color='k', linestyle='--', linewidth=0.5)

# B_y vs y
axes[0, 3].plot(yValues * 1000, coil_By_vs_y * 1000, 'b-', linewidth=2, label='Coil')
axes[0, 3].set_xlabel('y [mm]')
axes[0, 3].set_ylabel('$B_y$ [mT]')
axes[0, 3].set_title('Coil: $B_y$ vs y (at x=0.01)')
axes[0, 3].grid(True, alpha=0.3)
axes[0, 3].axhline(y=0, color='k', linestyle='--', linewidth=0.5)
axes[0, 3].axvline(x=0, color='k', linestyle='--', linewidth=0.5)


# Magnet plots (bottom row)
# B_x vs x
axes[1, 0].plot(xValues * 1000, magnet_Bx_vs_x * 1000, 'r-', linewidth=2, label='Magnet')
axes[1, 0].set_xlabel('x [mm]')
axes[1, 0].set_ylabel('$B_x$ [mT]')
axes[1, 0].set_title('Magnet: $B_x$ vs x (at y=0)')
axes[1, 0].grid(True, alpha=0.3)
axes[1, 0].axhline(y=0, color='k', linestyle='--', linewidth=0.5)
axes[1, 0].axvline(x=0, color='k', linestyle='--', linewidth=0.5)

# B_y vs x
axes[1, 1].plot(xValues * 1000, magnet_By_vs_x * 1000, 'r-', linewidth=2, label='Magnet')
axes[1, 1].set_ylim(-1.2, 4)
axes[1, 1].set_xlabel('x [mm]')
axes[1, 1].set_ylabel('$B_y$ [mT]')
axes[1, 1].set_title('Magnet: $B_y$ vs x (at y=0)')
axes[1, 1].grid(True, alpha=0.3)
axes[1, 1].axhline(y=0, color='k', linestyle='--', linewidth=0.5)
axes[1, 1].axvline(x=0, color='k', linestyle='--', linewidth=0.5)

# B_x vs y
axes[1, 2].plot(yValues * 1000, magnet_Bx_vs_y * 1000, 'r-', linewidth=2, label='Magnet')
axes[1, 2].set_xlabel('y [mm]')
axes[1, 2].set_ylabel('$B_x$ [mT]')
axes[1, 2].set_title('Magnet: $B_x$ vs y (at x=0)')
axes[1, 2].grid(True, alpha=0.3)
axes[1, 2].axhline(y=0, color='k', linestyle='--', linewidth=0.5)
axes[1, 2].axvline(x=0, color='k', linestyle='--', linewidth=0.5)

# B_y vs y
axes[1, 3].plot(yValues * 1000, magnet_By_vs_y * 1000, 'r-', linewidth=2, label='Magnet')
axes[1, 3].set_xlabel('y [mm]')
axes[1, 3].set_ylabel('$B_y$ [mT]')
axes[1, 3].set_title('Magnet: $B_y$ vs y (at x=0)')
axes[1, 3].grid(True, alpha=0.3)
axes[1, 3].axhline(y=0, color='k', linestyle='--', linewidth=0.5)
axes[1, 3].axvline(x=0, color='k', linestyle='--', linewidth=0.5)


plt.tight_layout(rect=[0, 0.03, 1, 0.96])
plt.savefig('images/field_comparison.png', dpi=150, bbox_inches='tight')
print('Plot saved as field_comparison.png')
plt.show()

